feat(docker): optimize init log output

diff --git a/docker/rootfs/etc/s6-overlay/s6-rc.d/init-010-update/run b/docker/rootfs/etc/s6-overlay/s6-rc.d/init-010-update/run
--- a/docker/rootfs/etc/s6-overlay/s6-rc.d/init-010-update/run
+++ b/docker/rootfs/etc/s6-overlay/s6-rc.d/init-010-update/run
@@ -1,6 +1,16 @@
 #!/usr/bin/with-contenv bash
 # shellcheck shell=bash
 
+function INFO() {
+    echo -e "[\033[32mINFO\033[0m] ${1}"
+}
+function ERROR() {
+    echo -e "[\033[31mERROR\033[0m] ${1}"
+}
+function WARN() {
+    echo -e "[\033[33mWARN\033[0m] ${1}"
+}
+
 # 更换国内软件源
 function package_cn {
 
@@ -8,7 +18,7 @@ function package_cn {
     sed -i "s/dl-cdn.alpinelinux.org/${ALPINE_MIRROR}/g" /etc/apk/repositories
     apk update -f
     if [ $? -ne 0 ]; then
-        echo "无法更换软件源，请更新镜像！"
+        ERROR "无法更换软件源，请更新镜像！"
         cp /etc/apk/repositories.bak /etc/apk/repositories
     fi
 
@@ -22,7 +32,7 @@ function package_cn_debian {
     echo "deb https://security.debian.org/debian-security bullseye-security main contrib non-free" >> /etc/apt/sources.list
     apt-get update -y
     if [ $? -ne 0 ]; then
-        echo "无法更换软件源，请更新镜像！"
+        ERROR "无法更换软件源，请更新镜像！"
         cp /etc/apt/sources.list.bak /etc/apt/sources.list
     fi
 
@@ -50,7 +60,7 @@ function package_update {
         hash_new=$(sha256sum /tmp/package_list_debian.txt)
         if [ "${hash_old}" != "${hash_new}" ]; then
             DEBIAN_FRONTEND="noninteractive"
-            echo "检测到package_list.txt有变化，更新软件包..."
+            INFO "检测到package_list.txt有变化，更新软件包..."
             if [ "${NASTOOL_CN_UPDATE}" = "true" ]; then
                 package_cn_debian
             else
@@ -58,9 +68,9 @@ function package_update {
             fi
             apt-get install -y $(echo $(cat /tmp/package_list_debian.txt))
             if [ $? -ne 0 ]; then
-                echo "无法更新软件包，请更新镜像！"
+                ERROR "无法更新软件包，请更新镜像！"
             else
-                echo "软件包安装成功"
+                INFO "软件包安装成功"
                 sha256sum /tmp/package_list_debian.txt > /tmp/package_list.txt.sha256sum
             fi
         fi
@@ -68,15 +78,15 @@ function package_update {
         hash_old=$(cat /tmp/package_list.txt.sha256sum)
         hash_new=$(sha256sum package_list.txt)
         if [ "${hash_old}" != "${hash_new}" ]; then
-            echo "检测到package_list.txt有变化，更新软件包..."
+            INFO "检测到package_list.txt有变化，更新软件包..."
             if [ "${NASTOOL_CN_UPDATE}" = "true" ]; then
                 package_cn
             fi
             apk add --no-cache $(echo $(cat package_list.txt))
             if [ $? -ne 0 ]; then
-                echo "无法更新软件包，请更新镜像！"
+                ERROR "无法更新软件包，请更新镜像！"
             else
-                echo "软件包安装成功"
+                INFO "软件包安装成功"
                 sha256sum package_list.txt > /tmp/package_list.txt.sha256sum
             fi
         fi
@@ -90,7 +100,7 @@ function requirements_update {
     hash_old=$(cat /tmp/requirements.txt.sha256sum)
     hash_new=$(sha256sum requirements.txt)
     if [ "${hash_old}" != "${hash_new}" ]; then
-        echo "检测到requirements.txt有变化，重新安装依赖..."
+        INFO "检测到requirements.txt有变化，重新安装依赖..."
         if [ "${NASTOOL_CN_UPDATE}" = "true" ]; then
             package_cn
             apk add --no-cache libffi-dev gcc musl-dev libxml2-dev libxslt-dev
@@ -102,10 +112,10 @@ function requirements_update {
             pip install -r requirements.txt
         fi
         if [ $? -ne 0 ]; then
-            echo "无法安装依赖，请更新镜像！"
+            ERROR "无法安装依赖，请更新镜像！"
             exit 1
         else
-            echo "依赖安装成功"
+            INFO "依赖安装成功"
             sha256sum requirements.txt > /tmp/requirements.txt.sha256sum
         fi
     fi
@@ -118,63 +128,57 @@ function third_party_update {
     hash_old=$(cat /tmp/third_party.txt.sha256sum)
     hash_new=$(sha256sum third_party.txt)
     if [ "${hash_old}" != "${hash_new}" ]; then
-        echo "检测到third_party.txt有变化，更新第三方组件..."
+        INFO "检测到third_party.txt有变化，更新第三方组件..."
         git submodule update --init --recursive
         if [ $? -ne 0 ]; then
-            echo "无法更新第三方组件，请更新镜像！"
+            ERROR "无法更新第三方组件，请更新镜像！"
             exit 1
         else
-            echo "第三方组件安装成功"
+            INFO "第三方组件安装成功"
             sha256sum third_party.txt > /tmp/third_party.txt.sha256sum
         fi
     fi
 
 }
 
-function __main {
+cd ${WORKDIR}
 
-    cd ${WORKDIR}
-
-    # 自动更新
-    if [ "${NASTOOL_AUTO_UPDATE}" = "true" ]; then
-        if [ ! -s /tmp/requirements.txt.sha256sum ]; then
-            sha256sum requirements.txt > /tmp/requirements.txt.sha256sum
-        fi
-        if [ ! -s /tmp/third_party.txt.sha256sum ]; then
-            sha256sum third_party.txt > /tmp/third_party.txt.sha256sum
-        fi
-        if [ ! -s /tmp/package_list.txt.sha256sum ]; then
-            sha256sum package_list.txt > /tmp/package_list.txt.sha256sum
-        fi
-        echo "更新主程序..."
-        git remote set-url origin "${REPO_URL}" &> /dev/null
-        echo "windows/" > .gitignore
-        # 更新分支
-        if [[ "${NASTOOL_VERSION}" == "dev" ]]; then
-            branch="dev"
-        else
-            branch="master"
-        fi
-
-        git clean -dffx
-        git fetch --depth 1 origin ${branch}
-        git reset --hard origin/${branch}
-
-        if [ $? -eq 0 ]; then
-            echo "主程序更新成功"
-            # 系统软件包更新
-            package_update
-            # Python依赖包更新
-            requirements_update
-            # third_party 更新
-            third_party_update
-        else
-            echo "更新失败，继续使用旧的程序来启动..."
-        fi
+# 自动更新
+if [ "${NASTOOL_AUTO_UPDATE}" = "true" ]; then
+    if [ ! -s /tmp/requirements.txt.sha256sum ]; then
+        sha256sum requirements.txt > /tmp/requirements.txt.sha256sum
+    fi
+    if [ ! -s /tmp/third_party.txt.sha256sum ]; then
+        sha256sum third_party.txt > /tmp/third_party.txt.sha256sum
+    fi
+    if [ ! -s /tmp/package_list.txt.sha256sum ]; then
+        sha256sum package_list.txt > /tmp/package_list.txt.sha256sum
+    fi
+    INFO "更新主程序..."
+    git remote set-url origin "${REPO_URL}" &> /dev/null
+    echo "windows/" > .gitignore
+    # 更新分支
+    if [[ "${NASTOOL_VERSION}" == "dev" ]]; then
+        branch="dev"
     else
-        echo "程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true"
+        branch="master"
     fi
 
-}
+    git clean -dffx
+    git fetch --depth 1 origin ${branch}
+    git reset --hard origin/${branch}
 
-__main 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"
+    if [ $? -eq 0 ]; then
+        INFO "主程序更新成功"
+        # 系统软件包更新
+        package_update
+        # Python依赖包更新
+        requirements_update
+        # third_party 更新
+        third_party_update
+    else
+        ERROR "更新失败，继续使用旧的程序来启动..."
+    fi
+else
+    INFO "程序自动升级已关闭，如需自动升级请在创建容器时设置环境变量：NASTOOL_AUTO_UPDATE=true"
+fi
